spring:
    data:
        mongodb:
            uri: mongodb+srv://jespinosa:skillstorm123@cluster1.bkdj4fp.mongodb.net/
            database: tax_prep
    output:
        ansi:
            enabled: ALWAYS

# javax:
#     net: 
#         ssl:
#             trustStore: /tmp/certs/rds-truststore.jks
#             trustStorePassword: skillstorm123

logging:
    level:
        com:
            skillstorm: debug
